apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
     labels: 
      app: mysql
    spec:
     containers:
      - name: database
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: devops1 
          - name: MYSQL_USER
            value: wpuser
          - name: MYSQL_PASSWORD 
            value: devops12345
          - name: MYSQL_DATABASE
            value: wpdb
        ports:
          - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector: 
    app: mysql