apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
      app: wordpress
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:php7.4-apache
          ports: 
            - containerPort: 80
              name: wordpress
          #volumeMounts:
          #  - name: wordpress-data
          #    mountPath: /var/www
          livenessProbe:
            httpGet:
              path: /
              port: 80
          env: 
            - name: WORDPRESS_DB_HOST # host db
              value: mysql-service.default.svc.cluster.local # read
            - name: WORDPRESS_DB_USER
              value: wpuser 
            - name: WORDPRESS_DB_PASSWORD
              value: devops12345
            - name: WORDPRESS_DB_NAME
              value: wpdb 
            - name: WORDPRESS_DEBUG
              value: "1"
      #volumes: 
      #  - name: wordpress-data
      #    hostPath:
      #    type:      
---
apiVersion: v1 
kind: Service 
metadata: 
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 80
